import type {Metadata} from 'next';
import {HeartHandshake,MessageCircle,Phone} from 'lucide-react';
import {LegalPage} from '@/components/legal-page';

export const metadata:Metadata={title:'Responsible Play — Loop',description:'Practical limits and confidential help for friendly golf side games.'};

export default function ResponsiblePlayPage(){return <LegalPage eyebrow="Keep the game friendly" title="The round matters more than the wager." intro="Loop records informal side-game balances. It does not accept bets, hold funds, move money, or decide whether a wager is legal where you play.">
 <aside className="help-now"><HeartHandshake size={28}/><div><h2>Help is available now</h2><p>If gambling is causing stress, secrecy, debt, or conflict, call or text the National Problem Gambling Helpline at <a href="tel:+18006973738"><strong>1-800-MY-RESET</strong></a>. Free, confidential help is available 24/7.</p><div><a className="primary" href="tel:+18006973738"><Phone size={17}/> Call for help</a><a className="secondary" href="sms:+18006973738"><MessageCircle size={17}/> Text for help</a></div><a className="legal-text-link" href="https://www.ncpgambling.org/chat/" target="_blank" rel="noreferrer">Open the confidential NCPG chat</a></div></aside>
 <section><h2>Before the first tee</h2><ul><li>Make sure every player understands the game, house rules, and value of each point or match.</li><li>Choose a whole-dollar amount that every player can comfortably lose.</li><li>Set a personal limit before play and do not raise it to chase a loss.</li><li>Keep essential money for housing, food, healthcare, and family needs out of the game.</li><li>Play only when it is legal for every participant.</li></ul></section>
 <section><h2>During the round</h2><ul><li>Anyone can ask to pause, lower the amount, or end the side game.</li><li>Use Loop’s activity history to review changes calmly with the group.</li><li>Avoid wagering when upset, under pressure, or affected by alcohol or other substances.</li><li>If weather or another problem ends the round, agree as a group whether partial results should count.</li></ul></section>
 <section><h2>Signs it may be time to stop</h2><p>Take a break and seek support if you are chasing losses, hiding play, borrowing money, missing obligations, feeling unable to stop, or arguing with people you care about because of gambling.</p></section>
 <section><h2>What Loop does and does not do</h2><p>Loop calculates scores and informal balances from the rules the group enters. Players handle any settlement outside the app. Loop does not provide payment links, credit, odds, gambling advice, or a guarantee that a side game complies with local law.</p></section>
 <section><h2>More help</h2><p>For confidential support and state-specific resources, visit the <a className="legal-text-link" href="https://www.ncpgambling.org/help-treatment/" target="_blank" rel="noreferrer">National Council on Problem Gambling help center</a>. If you or someone else is in immediate danger, call emergency services.</p></section>
 </LegalPage>}
