import {describe,it,expect} from 'vitest';import {Round,players,defaults,Hole,pars} from '../lib/types';import {defaultRules,sides,rulesSummary} from '../lib/rules';import {wolf} from '../lib/games/wolf';import {hammer} from '../lib/games/hammer';import {vegas} from '../lib/games/vegas';import {calculate} from '../lib/games';import {settle} from '../lib/settlement';import {simulate} from '../lib/simulation';import {nassau} from '../lib/games/nassau';
const h=(scores:number[],extra:Partial<Hole>={}):Hole=>({scores,greenie:null,sandies:[],dots:[],snake:null,...extra});
function round(games:Round['games'],results:Hole[],amount=2):Round{const rules=defaultRules();games.forEach(g=>rules.stakes[g]=amount);return {id:'r',course:'Bay Hill',date:'2026-09-17',holes:18,players:players.map(p=>({...p})),games,config:{...defaults,rules},results,presses:[],paid:[]}}
function zero(b:number[]){expect(Math.round(b.reduce((x,y)=>x+y,0)*100)).toBe(0);const left=[...b];settle(b).forEach(p=>{left[p.from]+=p.amount;left[p.to]-=p.amount});left.forEach(v=>expect(v).toBeCloseTo(0));}
describe('Wolf choices and customized stakes',()=>{
 it('partner win uses best ball and splits per-opponent transfers',()=>{const r=round(['Wolf'],[h([5,3,4,6],{wolf:{wolf:0,mode:'partner',partner:1}})]);expect(wolf(r).balances).toEqual([2,2,-2,-2]);zero(wolf(r).balances)});
 it('lone win and loss have independent multipliers',()=>{const win=round(['Wolf'],[h([3,4,5,6],{wolf:{wolf:0,mode:'lone'}})]);expect(wolf(win).balances).toEqual([12,-4,-4,-4]);const loss=round(['Wolf'],[h([5,4,5,6],{wolf:{wolf:0,mode:'lone'}})]);loss.config.rules!.wolfSoloLoss=3;expect(wolf(loss).balances).toEqual([-18,6,6,6]);zero(wolf(loss).balances)});
 it('blind win uses the blind multiplier and a custom hole stake',()=>{const r=round(['Wolf'],[h([3,4,5,6],{wolf:{wolf:0,mode:'blind',stake:1.25}})]);expect(wolf(r).balances).toEqual([15,-5,-5,-5]);zero(wolf(r).balances)});
 it('solo tie can push or lose by rule',()=>{const r=round(['Wolf'],[h([4,4,5,6],{wolf:{wolf:0,mode:'lone'}})]);expect(wolf(r).balances).toEqual([0,0,0,0]);r.config.rules!.wolfTie='wolf-loses';expect(wolf(r).balances).toEqual([-12,4,4,4])});
 it('three players split the pooled wager at cent precision',()=>{const r=round(['Wolf'],[h([3,4,5],{wolf:{wolf:0,mode:'partner',partner:1,stake:.01}})]);r.players=r.players.slice(0,3);expect(wolf(r).balances).toEqual([.01,0,-.01]);zero(wolf(r).balances)});
});
describe('Hammer decisions',()=>{
 it('accepted hammer doubles and best ball decides',()=>{const r=round(['Hammer'],[h([3,5,4,6],{hammer:[{by:'A',response:'accepted'}]})]);expect(hammer(r).balances).toEqual([2,2,-2,-2]);zero(hammer(r).balances)});
 it('decline concedes the pre-offer amount regardless of scores',()=>{const r=round(['Hammer'],[h([6,6,3,4],{hammer:[{by:'A',response:'declined'}]})]);expect(hammer(r).balances).toEqual([1,1,-1,-1]);expect(hammer(r).holes[0].label).toContain('concession')});
 it('alternating accepted throws and birdie option multiply',()=>{const r=round(['Hammer'],[h([3,5,4,6],{hammer:[{by:'A',response:'accepted'},{by:'B',response:'accepted'}]})]);r.config.rules!.hammerBirdie=true;expect(hammer(r).balances).toEqual([8,8,-8,-8]);zero(hammer(r).balances)});
 it('rejects duplicate-team and pending actions',()=>{const r=round(['Hammer'],[h([3,5,4,6],{hammer:[{by:'A',response:'accepted'},{by:'A',response:'accepted'}]})]);expect(()=>hammer(r)).toThrow();r.results[0].hammer=[{by:'B',response:'pending'}];expect(()=>hammer(r)).toThrow()});
});
describe('Vegas, config, compatibility',()=>{
 it('prices the configured point value and per-hole partner',()=>{const r=round(['Vegas'],[h([4,5,6,7],{vegasPartner:2})],.25);expect(vegas(r).holes[0].label).toContain('46 vs 57');expect(vegas(r).balances).toEqual([1.38,-1.38,1.37,-1.37]);zero(vegas(r).balances)});
 it('flips the opposing number when one side makes a gross birdie',()=>{const r=round(['Vegas'],[h([3,5,4,6])],1);r.config.rules!.vegasFlip=true;expect(vegas(r).holes[0].label).toContain('35 vs 64');zero(vegas(r).balances)});
 it('supports custom Nassau press thresholds and unequal but valid Hammer teams',()=>{const r=round(['Nassau'],[h([3,4,5,6])]);r.config.rules!.pressAt=1;r.config.rules!.pressLimit=1;expect(nassau(r).matches.filter(x=>x.press)).toHaveLength(1);r.config.rules!.teamA=[0];expect(sides(r).b).toEqual([1,2,3]);r.games=['Hammer'];expect(hammer(r).balances).toHaveLength(4)});
 it('pays every three-putt in event mode and only the final holder otherwise',()=>{const r=round(['Snake'],[h([4,4,4,4],{snake:2,snakeEvents:[1,2]})]);r.config.rules!.snakeMode='each';expect(calculate(r).balances).toEqual([4,-4,-4,4]);r.config.rules!.snakeMode='last';expect(calculate(r).balances).toEqual([2,2,-6,2]);zero(calculate(r).balances)});
 it('settles whole-round Match Play once after counting hole wins',()=>{const r=round(['Match Play'],[h([3,4,5,6]),h([4,4,5,6])],3);r.config.rules!.matchMode='round';expect(calculate(r).balances).toEqual([9,3,-3,-9]);zero(calculate(r).balances)});
 it('applies greenie par, eagle and sandy qualification rules',()=>{const r=round(['Greenies','Birdies','Sandies'],[h([5,4,4,4],{greenie:0,sandies:[0,1]})]);r.config.greenHoles=[1];r.config.rules!.greenPar=true;r.config.rules!.sandyPar=true;expect(calculate(r).balances).toEqual([-2,6,-2,-2]);r.results=[h([2,4,4,4])];r.config.rules!.eagleMultiplier=3;expect(calculate(r).ledger.find(x=>x.game==='Birdies')?.balances).toEqual([18,-6,-6,-6]);zero(calculate(r).balances)});
 it('keeps stored v1 rounds on their original Wolf behavior',()=>{const r=round(['Wolf'],[h([3,4,5,6])]);delete r.config.rules;expect(calculate(r).balances).toEqual([6,-2,-2,-2])});
 it('runs all configured games for 18 simulated holes and settles to zero',()=>{const r=round(['Nassau','Skins','Wolf','Match Play','Vegas','Hammer','Greenies','Birdies','Sandies','Snake','Dots'],[]);let seed=97;const random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};for(let i=0;i<20;i++){const result=simulate(r,18,random);expect(result.results).toHaveLength(18);expect(result.results.every((x,j)=>x.scores.every(v=>v>=1&&v<=pars[j]+4))).toBe(true);const b=calculate(result).balances;zero(b)}});
 it('summarizes the actual chosen stakes',()=>{const r=round(['Wolf'],[],7.5);expect(rulesSummary(r,'Wolf')).toContain('$7.5')});
});
