import type {Metadata} from 'next';
import {LegalPage} from '@/components/legal-page';

export const metadata:Metadata={title:'Privacy Policy — Round Settled',description:'How Round Settled collects, uses, shares, and protects account and golf data.'};

export default function PrivacyPage(){return <LegalPage eyebrow="Effective September 30, 2026" title="Privacy, in plain language." intro="Round Settled needs a small amount of personal information to save your golfer, rounds, groups, and preferences. This policy explains what is collected and what choices you have during the private beta.">
 <section><h2>The short version</h2><ul><li>Round Settled currently has no advertising and does not sell personal information.</li><li>Round Settled never holds or transfers wager money.</li><li>Your account, rounds, groups, and preferences are stored so they are available across your devices.</li><li>Group members see only the golf information and activity that a captain or organizer shares with them.</li></ul></section>
 <section><h2>Information Round Settled collects</h2><p><strong>Account and profile.</strong> Your name, email address, securely hashed password, handicap, home course, player color, distance preference, and default round settings.</p><p><strong>Guest access.</strong> A guest provides a display name when opening a valid invitation. Round Settled stores that name, a temporary guest-session cookie, the golfer the guest claims in a weekly game, and any shared changes the guest makes. Guests do not provide an email address or password.</p><p><strong>Golf activity.</strong> Courses and tees, players, scores, game choices, whole-dollar wager settings, calculated balances, settlement status, saved home games, group rosters, events, trips, and an activity record showing who changed shared scores or settings.</p><p><strong>Device and session data.</strong> An essential sign-in or guest cookie keeps your session available. A signed-in player also has a local browser copy of basic account profile and golf data so the latest scorecard remains available if the connection drops. Signing out removes that account copy from the browser. Round Settled does not currently use advertising cookies or third-party analytics.</p><p><strong>Location when you ask for it.</strong> If you tap <em>Use my location</em> in the course finder, your browser asks permission and sends your coordinates to OpenGolfAPI to find nearby courses. Round Settled does not save those coordinates to your account.</p></section>
 <section><h2>How Round Settled uses information</h2><ul><li>To create and secure your account.</li><li>To save your preferences, rounds, stats, groups, and home-game setups.</li><li>To calculate handicaps, game results, balances, settlements, and season history.</li><li>To synchronize a shared round or weekly game across the group’s devices.</li><li>To diagnose failures, prevent misuse, and improve the private beta.</li></ul></section>
 <section><h2>When information is shared</h2><p>Round Settled shares round and group information with people who receive a valid invitation link and either sign in or continue as a guest. The captain chooses whether an invitation allows viewing or editing. Shared activity can identify the account or guest name that made an update so the group can review changes.</p><p>Round Settled uses Hostinger to host the app and database. Nearby course searches use OpenGolfAPI, whose course records may include data from OpenStreetMap contributors. These providers process only the information needed to provide their service.</p><p>Round Settled may disclose information when required by law, to protect users or the service, or as part of a future business transfer. A future owner would remain responsible for this policy or would notify users of material changes.</p></section>
 <section><h2>Retention and deletion</h2><p>Account and golf data are kept while your account is active so your history remains available. Guest sessions expire after 30 days. A guest name and accepted activity may remain with a shared round or weekly game so the group can review who changed a score or lineup. Shared links can expire or be revoked.</p><p>You can permanently delete your account from Player settings. Deletion removes your sign-in, email, profile, private preferences, saved app data, and support requests. Shared scorecards may retain an anonymous “Former player” entry so other players’ scores and balances remain accurate. Copies that other people already exported are outside Round Settled’s control.</p><p>Use the <a className="legal-text-link" href="/support">support form</a> to ask for access, correction, or help with deletion. Deleting browser data removes only the offline copy; signing out also clears Round Settled’s local account cache on that device.</p></section>
 <section><h2>Security</h2><p>Round Settled uses encrypted connections, one-way password hashing, protected session tokens, and access checks for shared data. No online service can promise perfect security. Use a unique password and stop a shared link if it reaches the wrong person.</p></section>
 <section><h2>Children and wager features</h2><p>Round Settled is not directed to children under 13. Side-game and wager features are intended only for adults who may lawfully use them. Parents or guardians who believe a child submitted personal information should contact the beta organizer who provided access.</p></section>
 <section><h2>Your choices</h2><p>You can change your name, handicap, course, color, distance unit, starting wager, and password in Profile. You can verify your email, request password recovery, or delete your account from the same area. You can deny location access and search for a course manually. Captains can revoke shared links and choose who may edit.</p></section>
 <section><h2>Changes to this policy</h2><p>Round Settled will update the effective date and give clear notice before a material change affects how existing personal information is used.</p></section>
 </LegalPage>}
