'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {ArrowRight,CheckCircle2,KeyRound,MailCheck} from 'lucide-react';
import {BrandLockup} from '@/components/brand-lockup';

export function ForgotPasswordForm(){
 const [email,setEmail]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState<'sent'|'unavailable'|null>(null),[error,setError]=useState('');
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/v1/auth/password-reset/request',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email})});const body=await response.json() as {delivery?:'sent'|'unavailable';error?:string};if(!response.ok)throw new Error(body.error||'Recovery could not be started.');setResult(body.delivery??'sent')}catch(cause){setError(cause instanceof Error?cause.message:'Recovery could not be started.')}finally{setBusy(false)}}
 if(result)return <RecoveryCard icon={<MailCheck/>} title={result==='sent'?'Check your email.':'Email recovery is being connected.'}><p>{result==='sent'?'If an active Round Settled account uses that address, a reset link will arrive shortly. The link works for 30 minutes.':'Your account is safe. Email delivery is not configured for this beta site yet, so send a support request and include the email on your account.'}</p>{result==='unavailable'&&<Link className="primary recovery-action" href="/support">Contact Round Settled support <ArrowRight/></Link>}<Link className="text-button recovery-back" href="/">Back to sign in</Link></RecoveryCard>;
 return <RecoveryCard icon={<KeyRound/>} title="Reset your password."><p>Enter the email used for Round Settled. We will send a secure link if that account is active.</p><form className="recovery-form" onSubmit={submit}><label>Email address<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@example.com"/></label>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Checking…':'Send reset link'} {!busy&&<ArrowRight/>}</button></form><Link className="text-button recovery-back" href="/">Back to sign in</Link></RecoveryCard>;
}

export function ResetPasswordForm({token}:{token:string}){
 const [password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[complete,setComplete]=useState(false),[error,setError]=useState('');
 async function submit(event:FormEvent){event.preventDefault();setError('');if(password!==confirmation){setError('The two passwords do not match.');return}setBusy(true);try{const response=await fetch('/api/v1/auth/password-reset/confirm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,password})});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||'Password could not be reset.');setComplete(true)}catch(cause){setError(cause instanceof Error?cause.message:'Password could not be reset.')}finally{setBusy(false)}}
 if(!token)return <RecoveryCard icon={<KeyRound/>} title="This link is incomplete."><p>Ask Round Settled for a new password reset link, then open the complete link from your email.</p><Link className="primary recovery-action" href="/forgot-password">Request a new link</Link></RecoveryCard>;
 if(complete)return <RecoveryCard icon={<CheckCircle2/>} title="Password changed."><p>You are securely signed in on this device. Other signed-in devices were disconnected.</p><Link className="primary recovery-action" href="/">Open Round Settled <ArrowRight/></Link></RecoveryCard>;
 return <RecoveryCard icon={<KeyRound/>} title="Choose a new password."><p>Use at least 10 characters and avoid a password you use on another site.</p><form className="recovery-form" onSubmit={submit}><label>New password<input type={show?'text':'password'} autoComplete="new-password" minLength={10} maxLength={128} required value={password} onChange={event=>setPassword(event.target.value)}/></label><label>Enter it again<input type={show?'text':'password'} autoComplete="new-password" minLength={10} maxLength={128} required value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><label className="recovery-check"><input type="checkbox" checked={show} onChange={event=>setShow(event.target.checked)}/> Show passwords</label>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save new password'} {!busy&&<ArrowRight/>}</button></form></RecoveryCard>;
}

export function VerifyEmailCard({token}:{token:string}){
 const sent=useRef(false),[status,setStatus]=useState<'working'|'complete'|'error'>(token?'working':'error'),[message,setMessage]=useState(token?'Checking your secure link…':'This verification link is incomplete.');
 useEffect(()=>{if(!token||sent.current)return;sent.current=true;fetch('/api/v1/auth/email-verification/confirm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})}).then(async response=>{const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||'Email could not be verified.');setStatus('complete');setMessage('Your email is verified. Thank you.')}).catch(cause=>{setStatus('error');setMessage(cause instanceof Error?cause.message:'Email could not be verified.')})},[token]);
 return <RecoveryCard icon={status==='complete'?<CheckCircle2/>:<MailCheck/>} title={status==='working'?'Verifying your email…':status==='complete'?'Email verified.':'We could not verify this link.'}><p role={status==='error'?'alert':'status'}>{message}</p><Link className="primary recovery-action" href="/">{status==='complete'?'Open Round Settled':'Return to Round Settled'} <ArrowRight/></Link></RecoveryCard>;
}

function RecoveryCard({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <main id="main-content" className="recovery-page"><header><Link className="auth-brand" href="/"><BrandLockup/></Link><Link href="/support">Need help?</Link></header><section className="recovery-card"><span className="recovery-icon">{icon}</span><h1>{title}</h1>{children}</section></main>}
