'use client';
import {useState,type FormEvent} from 'react';
import {Check,KeyRound,LogOut,Save,Settings} from 'lucide-react';
import type {Account} from '@/lib/account';

export function AccountSettings({account,onSaved,onLogout}:{account:Account;onSaved:(account:Account)=>void;onLogout:()=>void}){
 const [form,setForm]=useState({displayName:account.displayName,handicap:String(account.handicap),...account.preferences});
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[passwords,setPasswords]=useState({currentPassword:'',newPassword:''});
 async function save(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');try{const response=await fetch('/api/v1/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({displayName:form.displayName,handicap:Number(form.handicap),preferences:{defaultHoles:Number(form.defaultHoles),defaultWager:Number(form.defaultWager),homeCourse:form.homeCourse,distanceUnit:form.distanceUnit,color:form.color}})});const result=await response.json() as {account?:Account;error?:string};if(!response.ok||!result.account)throw new Error(result.error||'Profile could not be saved.');onSaved(result.account);setMessage('Preferences saved online.')}catch(cause){setMessage(cause instanceof Error?cause.message:'Profile could not be saved.')}finally{setBusy(false)}}
 async function changePassword(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');try{const response=await fetch('/api/v1/profile/password',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(passwords)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Password could not be changed.');setPasswords({currentPassword:'',newPassword:''});setMessage('Password changed. Other devices were signed out.')}catch(cause){setMessage(cause instanceof Error?cause.message:'Password could not be changed.')}finally{setBusy(false)}}
 return <section className="account-settings"><div className="account-settings-title"><span><Settings/></span><div><strong>Player settings</strong><small>{account.email}</small></div></div><form onSubmit={save}><div className="settings-grid"><label>Name<input required minLength={2} maxLength={80} value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>Handicap index<input required type="number" inputMode="decimal" step="0.1" min="-10" max="54" value={form.handicap} onChange={e=>setForm({...form,handicap:e.target.value})}/></label><label>Default holes<select value={form.defaultHoles} onChange={e=>setForm({...form,defaultHoles:Number(e.target.value) as 9|18})}><option value={9}>9 holes</option><option value={18}>18 holes</option></select></label><label>Starting wager<input required type="number" inputMode="decimal" step="0.5" min="0" max="10000" value={form.defaultWager} onChange={e=>setForm({...form,defaultWager:Number(e.target.value)})}/></label><label className="settings-wide">Home course<input maxLength={180} value={form.homeCourse} onChange={e=>setForm({...form,homeCourse:e.target.value})} placeholder="Optional"/></label><label>Distance<select value={form.distanceUnit} onChange={e=>setForm({...form,distanceUnit:e.target.value as 'yards'|'meters'})}><option value="yards">Yards</option><option value="meters">Meters</option></select></label><label>Player color<span className="color-input"><input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/><span>{form.color.toUpperCase()}</span></span></label></div><button className="primary settings-save" disabled={busy}><Save/> {busy?'Saving…':'Save preferences'}</button></form>{message&&<p className="settings-message" role="status"><Check/> {message}</p>}<details className="password-settings"><summary><KeyRound/> Change password</summary><form onSubmit={changePassword}><label>Current password<input type="password" autoComplete="current-password" required value={passwords.currentPassword} onChange={e=>setPasswords({...passwords,currentPassword:e.target.value})}/></label><label>New password<input type="password" autoComplete="new-password" minLength={10} maxLength={128} required value={passwords.newPassword} onChange={e=>setPasswords({...passwords,newPassword:e.target.value})}/></label><button className="secondary" disabled={busy}>Update password</button></form></details><button className="logout-button" onClick={onLogout}><LogOut/> Sign out of Loop</button></section>
}
