'use client';
import {useState,type FormEvent} from 'react';
import {AlertTriangle,Check,HeartHandshake,KeyRound,LifeBuoy,LogOut,MailCheck,Save,Settings,ShieldCheck,Trash2} from 'lucide-react';
import type {Account} from '@/lib/account';

export function AccountSettings({account,onSaved,onLogout}:{account:Account;onSaved:(account:Account)=>void;onLogout:()=>void}){
 const [form,setForm]=useState({displayName:account.displayName,handicap:String(account.handicap),...account.preferences,defaultWager:Math.round(account.preferences.defaultWager)});
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[passwords,setPasswords]=useState({currentPassword:'',newPassword:''});
 const [deletion,setDeletion]=useState({password:'',confirmation:''}),[deleteError,setDeleteError]=useState(''),[deleting,setDeleting]=useState(false);

 async function save(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');try{const response=await fetch('/api/v1/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({displayName:form.displayName,handicap:Number(form.handicap),preferences:{defaultHoles:Number(form.defaultHoles),defaultWager:Number(form.defaultWager),homeCourse:form.homeCourse,distanceUnit:form.distanceUnit,color:form.color}})});const result=await response.json() as {account?:Account;error?:string};if(!response.ok||!result.account)throw new Error(result.error||'Profile could not be saved.');onSaved(result.account);setMessage('Preferences saved online.')}catch(cause){setMessage(cause instanceof Error?cause.message:'Profile could not be saved.')}finally{setBusy(false)}}
 async function changePassword(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');try{const response=await fetch('/api/v1/profile/password',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(passwords)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Password could not be changed.');setPasswords({currentPassword:'',newPassword:''});setMessage('Password changed. Other devices were signed out.')}catch(cause){setMessage(cause instanceof Error?cause.message:'Password could not be changed.')}finally{setBusy(false)}}
 async function verifyEmail(){setBusy(true);setMessage('');try{const response=await fetch('/api/v1/auth/email-verification/request',{method:'POST'});const result=await response.json() as {delivery?:'sent'|'unavailable'|'verified';error?:string};if(!response.ok)throw new Error(result.error||'Verification could not be started.');setMessage(result.delivery==='sent'?`Verification sent to ${account.email}.`:result.delivery==='verified'?'Your email is already verified.':'Email delivery is being connected for the beta. Your account still works normally.')}catch(cause){setMessage(cause instanceof Error?cause.message:'Verification could not be started.')}finally{setBusy(false)}}
 async function deleteAccount(event:FormEvent){event.preventDefault();setDeleteError('');if(deletion.confirmation!=='DELETE'){setDeleteError('Type DELETE exactly to continue.');return}setDeleting(true);try{const response=await fetch('/api/v1/profile/delete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(deletion)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Account could not be deleted.');onLogout()}catch(cause){setDeleteError(cause instanceof Error?cause.message:'Account could not be deleted.');setDeleting(false)}}

 return <section className="account-settings"><div className="account-settings-title"><span><Settings/></span><div><strong>Player settings</strong><small>{account.email}</small></div></div>
  <div className={`verification-status ${account.emailVerified?'verified':''}`}><MailCheck/><div><strong>{account.emailVerified?'Email verified':'Verify your email'}</strong><small>{account.emailVerified?'Recovery and account notices can reach you.':'Verification protects recovery and future group invitations.'}</small></div>{!account.emailVerified&&<button type="button" className="secondary" disabled={busy} onClick={verifyEmail}>Send link</button>}</div>
  <form onSubmit={save}><div className="settings-grid"><label>Name<input required minLength={2} maxLength={80} value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>Handicap index<input required type="number" inputMode="decimal" step="0.1" min="-10" max="54" value={form.handicap} onChange={e=>setForm({...form,handicap:e.target.value})}/></label><label>Default holes<select value={form.defaultHoles} onChange={e=>setForm({...form,defaultHoles:Number(e.target.value) as 9|18})}><option value={9}>9 holes</option><option value={18}>18 holes</option></select></label><label>Starting wager<input required type="number" inputMode="numeric" step="1" min="0" max="10000" value={form.defaultWager} onChange={e=>setForm({...form,defaultWager:Math.max(0,Math.min(10000,Math.round(Number(e.target.value))))})}/></label><label className="settings-wide">Home course<input maxLength={180} value={form.homeCourse} onChange={e=>setForm({...form,homeCourse:e.target.value})} placeholder="Optional"/></label><label>Distance<select value={form.distanceUnit} onChange={e=>setForm({...form,distanceUnit:e.target.value as 'yards'|'meters'})}><option value="yards">Yards</option><option value="meters">Meters</option></select></label><label>Player color<span className="color-input"><input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/><span>{form.color.toUpperCase()}</span></span></label></div><button className="primary settings-save" disabled={busy}><Save/> {busy?'Saving…':'Save preferences'}</button></form>
  {message&&<p className="settings-message" role="status"><Check/> {message}</p>}
  <details className="password-settings"><summary><KeyRound/> Change password</summary><form onSubmit={changePassword}><label>Current password<input type="password" autoComplete="current-password" required value={passwords.currentPassword} onChange={e=>setPasswords({...passwords,currentPassword:e.target.value})}/></label><label>New password<input type="password" autoComplete="new-password" minLength={10} maxLength={128} required value={passwords.newPassword} onChange={e=>setPasswords({...passwords,newPassword:e.target.value})}/></label><button className="secondary" disabled={busy}>Update password</button></form></details>
  <nav className="account-support-links" aria-label="Account help and policies"><a href="/support"><LifeBuoy/> Get help</a><a href="/privacy"><ShieldCheck/> Privacy policy</a><a href="/responsible-play"><HeartHandshake/> Responsible play</a></nav>
  <details className="delete-settings"><summary><Trash2/> Delete account and personal data</summary><div className="delete-explainer"><AlertTriangle/><p>This permanently removes your sign-in, profile, private preferences, and saved app data. Shared scorecards may keep an anonymous “Former player” entry so the group’s scores and balances still add up.</p></div><form onSubmit={deleteAccount}><label>Current password<input type="password" autoComplete="current-password" required maxLength={128} value={deletion.password} onChange={event=>setDeletion({...deletion,password:event.target.value})}/></label><label>Type DELETE to confirm<input required autoComplete="off" value={deletion.confirmation} onChange={event=>setDeletion({...deletion,confirmation:event.target.value})}/></label>{deleteError&&<p className="auth-error" role="alert">{deleteError}</p>}<button className="danger-button" disabled={deleting}>{deleting?'Deleting…':'Permanently delete my account'}</button></form></details>
  <button className="logout-button" onClick={onLogout}><LogOut/> Sign out of Round Settled</button>
 </section>;
}
