'use client';
import {FormEvent,useState} from 'react';
import {Check,ChevronRight,LocateFixed,MapPin,Search} from 'lucide-react';
import {CourseTee} from '@/lib/types';
import {CourseDetail,CourseSearchResult,courseTeeFrom,getCourse,nearbyCourses,searchCourses} from '@/lib/course-api';

export function CourseFinder({onChoose,onToast}:{onChoose:(name:string,tee:CourseTee,holes:9|18)=>void;onToast:(message:string)=>void}){
 const [query,setQuery]=useState(''),[results,setResults]=useState<CourseSearchResult[]>([]),[detail,setDetail]=useState<CourseDetail|null>(null),[selectedTeeKey,setSelectedTeeKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function find(event?:FormEvent){event?.preventDefault();if(query.trim().length<2){setError('Enter at least two letters from the course name.');return}setBusy(true);setError('');setDetail(null);setSelectedTeeKey('');try{const courses=await searchCourses(query);setResults(courses);if(!courses.length)setError('No matching courses found. Try a shorter name.')}catch{setError('Course search is unavailable right now. You can still enter the course manually.')}finally{setBusy(false)}}
 function nearMe(){if(!navigator.geolocation){setError('Location is not available in this browser.');return}setBusy(true);setError('');setDetail(null);setSelectedTeeKey('');navigator.geolocation.getCurrentPosition(async position=>{try{const courses=await nearbyCourses(position.coords.latitude,position.coords.longitude);setResults(courses);if(!courses.length)setError('No courses were found within 25 miles.')}catch{setError('Nearby course search is unavailable right now.')}finally{setBusy(false)}},()=>{setBusy(false);setError('Location was not shared. Search by course name instead.')},{enableHighAccuracy:false,timeout:10000,maximumAge:300000})}
 async function openCourse(course:CourseSearchResult){setBusy(true);setError('');try{const full=await getCourse(course.id);setDetail(full);if(!full.tees?.length)setError('This course does not have tee ratings yet. You can enter them manually below.')}catch{setError('Tee data could not be loaded for this course.')}finally{setBusy(false)}}
 function choose(tee:CourseDetail['tees'][number]){if(!detail)return;setSelectedTeeKey(tee.tee_key);const holes:9|18=detail.holes===9?9:18;onChoose(detail.course_name,courseTeeFrom(detail,tee),holes);onToast(`${detail.course_name} · ${tee.tee_name} tees selected`)}
 return <section className="course-finder"><div className="course-finder-title"><span><MapPin size={18}/></span><div><strong>Find your course</strong><small>Load tees, ratings, slope, pars, and hole handicaps.</small></div></div><form className="course-search" onSubmit={find}><label>Course name<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Try Bay Hill or Pebble Beach"/></label><button className="primary" disabled={busy} type="submit"><Search size={16}/>{busy?'Searching…':'Search'}</button></form><button className="secondary location-search" disabled={busy} onClick={nearMe}><LocateFixed size={17}/> Use my location</button><p className="course-privacy">Your location is shared once with OpenGolfAPI to find courses within 25 miles. Loop does not save it.</p>{error&&<p className="error">{error}</p>}{!detail&&results.length>0&&<div className="course-results">{results.map(course=><button key={course.id} onClick={()=>openCourse(course)}><span><strong>{course.course_name}</strong><small>{course.city}, {course.state}{course.distance_mi!==undefined?` · ${course.distance_mi.toFixed(1)} mi`:''}</small></span><span>Select</span></button>)}</div>}{detail&&<div className="tee-picker"><div className="tee-picker-heading"><div><strong>{detail.course_name}</strong><small>{detail.city}, {detail.state}</small></div><button className="text-button" onClick={()=>{setDetail(null);setSelectedTeeKey('')}}>Change course</button></div><p>Choose the tees your group is playing.</p>{detail.tees.map(tee=>{const selected=selectedTeeKey===tee.tee_key;return <button className={selected?'selected':''} aria-pressed={selected} key={tee.tee_key} onClick={()=>choose(tee)}><span className="tee-color" style={{background:tee.tee_color||'#d9dfd2'}}/><span><strong>{tee.tee_name}</strong><small>{tee.gender} · {tee.yardage.toLocaleString()} yards</small></span><span className="tee-numbers"><b>{tee.course_rating}</b> / {tee.slope}<small>rating / slope</small></span>{selected?<Check size={17}/>:<ChevronRight size={17}/>}</button>})}</div>}<p className="course-attribution">Course data by OpenGolfAPI and OpenStreetMap contributors, ODbL 1.0. Confirm details with the course scorecard.</p></section>
}
