'use client';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Shuffle,SlidersHorizontal} from 'lucide-react';
import {gameCatalog} from '@/lib/game-catalog';
import {CaddieInput,ComplexityPreference,Recommendation,recommendGames,RoundVibe,TeamPreference} from '@/lib/recommendations/gameCaddie';
import {Game,Player,Round,players as demoPlayers} from '@/lib/types';import {HouseRule} from '@/lib/product-model';import {gameFits} from '@/lib/game-catalog';import {estimateExposure} from '@/lib/games/exposure';import {newRound} from '@/lib/demo';
const vibes:{id:RoundVibe;name:string;detail:string}[]=[
  {id:'friendly',name:'Keep it friendly',detail:'Simple rules and less money movement.'},
  {id:'competitive',name:'Competitive',detail:'Balanced games with action throughout.'},
  {id:'chaos',name:'Chaos',detail:'Presses, doubles and more decisions.'},
  {id:'team',name:'Team battle',detail:'Fixed or rotating partners.'},
  {id:'new',name:'Try something new',detail:'Favor games this group rarely plays.'},
  {id:'quick',name:'Quick nine',detail:'Fast choices that fit a shorter round.'}
];
const titles=['How many golfers?','How long is the round?','Who is playing?','What kind of round?','Maximum exposure','Keep the rules how simple?','Playing individually or as teams?'];
const steps=['Players','Holes','Lineup','Vibe','Exposure','Complexity','Teams'];
function lineupFor(count:number,roster:Player[]){return Array.from({length:count},(_,index)=>roster[index]?{...roster[index]}:{id:`guest-${index}`,name:`Player ${index+1}`,handicap:18,color:'#e2e6d5'})}

export function GameCaddie({history,roster,onBack,onPlay,onRules,houseRules=[],onPlayRule}:{history:Round[];roster:Player[];onBack:()=>void;onPlay:(recommendation:Recommendation,input:CaddieInput)=>void;onRules:(game:Game)=>void;houseRules?:HouseRule[];onPlayRule?:(rule:HouseRule)=>void}){
  const [step,setStep]=useState(0),[count,setCount]=useState(4),[holes,setHoles]=useState<9|18>(18);
  const [lineup,setLineup]=useState<Player[]>(()=>lineupFor(4,roster.length?roster:demoPlayers));
  const [vibe,setVibe]=useState<RoundVibe>('competitive'),[maxExposure,setMaxExposure]=useState(20),[complexity,setComplexity]=useState<ComplexityPreference>('medium'),[teams,setTeams]=useState<TeamPreference>('any');
  const [excluded,setExcluded]=useState<Game[]>([]),[results,setResults]=useState(false);
  const input:CaddieInput={players:lineup,holes,vibe,maxExposure,complexity,teams,history};
  const candidates=recommendGames(input,excluded);
  const three=candidates.slice(0,3);
  const moreAvailable=recommendGames(input,[...excluded,...three.map(item=>item.game)]).length>=3;
  const savedRule=vibe==='new'?undefined:houseRules.find(rule=>rule.holes===holes&&rule.games.every(game=>gameFits(game,count,holes))&&rule.games.reduce((total,game)=>total+estimateExposure({...newRound(),players:lineup,holes,games:rule.games,config:rule.config},game).possibleMax,0)<=maxExposure);
  function changeCount(next:number){setCount(next);setLineup(lineupFor(next,roster.length?roster:demoPlayers))}
  function updatePlayer(index:number,patch:Partial<Player>){setLineup(current=>current.map((player,i)=>i===index?{...player,...patch}:player))}
  function showMore(){setExcluded(previous=>[...previous,...three.map(item=>item.game)])}
  return <div className="caddie-screen"><button className="text-button" onClick={()=>results?setResults(false):step?setStep(step-1):onBack()}><ArrowLeft size={16}/> Back</button>
    <div className="caddie-heading"><span className="eyebrow">GAME CADDIE</span><h1>{results?'Three games for today.':titles[step]}</h1><p>{results?`${count} players · ${holes} holes · $${maxExposure} maximum exposure target`:'A few details help us find games that fit your group.'}</p></div>
    {!results?<><div className="caddie-progress">{steps.map((label,index)=><span key={label} className={index<=step?'selected':''} aria-label={`${label}${index===step?' current':''}`}/>)}</div>
      {step===0&&<div className="caddie-options two">{[2,3,4,5,6,7,8].map(number=><button key={number} className={count===number?'selected':''} aria-pressed={count===number} onClick={()=>changeCount(number)}>{number===8?'8 golfers':`${number} golfers`}</button>)}</div>}
      {step===1&&<div className="caddie-options two">{([9,18] as const).map(number=><button key={number} className={holes===number?'selected':''} aria-pressed={holes===number} onClick={()=>setHoles(number)}><strong>{number}</strong><small>holes</small></button>)}</div>}
      {step===2&&<><p className="fine">Choose a saved golfer for each slot, or type a new name. Handicaps are optional.</p><div className="caddie-lineup">{lineup.map((player,index)=><div key={index}><label>Golfer {index+1}<select aria-label={`Saved golfer ${index+1}`} value={roster.some(saved=>saved.id===player.id)?player.id:'custom'} onChange={event=>{const saved=roster.find(saved=>saved.id===event.target.value);updatePlayer(index,saved??{id:`guest-${index}`,name:`Player ${index+1}`,handicap:18})}}>{roster.map(saved=><option key={saved.id} value={saved.id}>{saved.name}</option>)}<option value="custom">New golfer</option></select></label><label>Name<input aria-label={`Golfer ${index+1} name`} value={player.name} maxLength={20} onChange={event=>updatePlayer(index,{name:event.target.value,id:`guest-${index}`})}/></label><label>HCP<input aria-label={`Golfer ${index+1} handicap`} type="number" min="0" max="54" value={player.handicap} onChange={event=>updatePlayer(index,{handicap:Math.max(0,Math.min(54,Math.round(Number(event.target.value))))})}/></label></div>)}</div></>}
      {step===3&&<div className="caddie-options">{vibes.map(option=><button key={option.id} className={vibe===option.id?'selected':''} aria-pressed={vibe===option.id} onClick={()=>setVibe(option.id)}><strong>{option.name}</strong><small>{option.detail}</small></button>)}</div>}
      {step===4&&<><p className="fine">What is the most any one player should reasonably be able to lose? Estimates help choose settings; they do not enforce a hard cap.</p><div className="caddie-options exposure-choices">{[5,10,20,25,50].map(amount=><button key={amount} className={maxExposure===amount?'selected':''} aria-pressed={maxExposure===amount} onClick={()=>setMaxExposure(amount)}>${amount}</button>)}</div><label className="caddie-custom">Custom maximum ($)<input type="number" min="1" max="10000" step="1" value={maxExposure} onChange={event=>setMaxExposure(Math.max(1,Math.min(10000,Math.round(Number(event.target.value)))))}/></label></>}
      {step===5&&<div className="caddie-options">{([['simple','Simple','Few decisions during the round.'],['medium','Medium','Some strategy without slowing play.'],['any','I don’t care','Show the best fit, whatever the rules.']] as const).map(([value,label,detail])=><button key={value} className={complexity===value?'selected':''} aria-pressed={complexity===value} onClick={()=>setComplexity(value)}><strong>{label}</strong><small>{detail}</small></button>)}</div>}
      {step===6&&<div className="caddie-options">{([['individual','Individual','Everyone plays for themselves.'],['teams','Teams','Play in fixed or rotating pairs.'],['any','No preference','Find the best game either way.']] as const).map(([value,label,detail])=><button key={value} className={teams===value?'selected':''} aria-pressed={teams===value} onClick={()=>setTeams(value)}><strong>{label}</strong><small>{detail}</small></button>)}</div>}
      <button className="primary full caddie-next" disabled={lineup.some(player=>!player.name.trim())} onClick={()=>{if(step<6)setStep(step+1);else{setExcluded([]);setResults(true)}window.scrollTo(0,0)}}>{step===6?'Find my games':'Continue'} <ArrowRight size={17}/></button></>:<><p className="caddie-rationale">These formats fit your group size, round length, preferences and modeled exposure. The dollar range is a projection, not a hard limit.</p><div className="caddie-recommendations">{three.map(item=>{const record=gameCatalog.find(game=>game.name===item.game)!;return <article key={item.game}><div className="recommendation-top"><span className="eyebrow">{item.metadata.complexity.toUpperCase()} · {item.metadata.teamType.toUpperCase()}</span><span className="risk-pill">${Math.round(item.exposure.projectedLow)}–${Math.round(item.exposure.projectedHigh)} projected</span></div><h2>{item.game}</h2><p>{record.description}</p><div className="recommendation-why"><strong>Why it fits</strong><span>{item.why}</span></div><div className="recommendation-meta"><span>Modeled possible max: ${Math.ceil(item.exposure.possibleMax)}</span><span>{item.metadata.tags.slice(0,2).join(' · ')}</span></div><div className="recommendation-actions"><button className="primary" onClick={()=>onPlay(item,input)}>Play this <ArrowRight size={15}/></button><button className="secondary" onClick={()=>onRules(item.game)}>How it works</button></div></article>})}</div>{savedRule&&<article className="feature-card caddie-saved"><span className="eyebrow">FROM YOUR HOUSE RULES</span><h2>{savedRule.name}</h2><p>{savedRule.games.join(' + ')} · {savedRule.holes} holes. Your group already knows this one.</p><button className="secondary" onClick={()=>onPlayRule?.(savedRule)}>Use this setup <ArrowRight size={15}/></button></article>}<div className="caddie-result-actions"><button className="secondary" disabled={!moreAvailable} onClick={showMore}><SlidersHorizontal size={16}/> Show me 3 more</button><button className="secondary" disabled={!three.length} onClick={()=>onPlay(three[Math.floor(Math.random()*three.length)],input)}><Shuffle size={16}/> Surprise me</button></div><p className="fine">The amount is a planning estimate. Changing values or per-hole decisions can increase what a player owes. Review the settings with your group before playing.</p></>}
    <div className="caddie-foot"><Check size={14}/> No money moves through Loop.</div>
  </div>
}
