'use client';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Plus} from 'lucide-react';
import {GameSettings,setupError} from './game-settings';
import {gameCatalog,gameFits} from '@/lib/game-catalog';
import {estimateExposure} from '@/lib/games/exposure';
import {newRound} from '@/lib/demo';
import {defaultRules,rulesSummary} from '@/lib/rules';
import {Game,Round,players as demoPlayers} from '@/lib/types';

export function GameCreator({onBack,onSave}:{onBack:()=>void;onSave:(name:string,round:Round)=>void}){
 const [name,setName]=useState(''),[round,setRound]=useState<Round>(()=>({...newRound(),games:['Skins'],config:{...newRound().config,rules:defaultRules()}}));
 const valid=!setupError(round)&&name.trim().length>0&&round.games.length>0;
 function setCount(count:number){setRound(previous=>({...previous,players:Array.from({length:count},(_,index)=>demoPlayers[index]??{id:`creator-${index}`,name:`Player ${index+1}`,handicap:18,color:'#e2e6d5'}),games:previous.games.filter(game=>gameFits(game,count,previous.holes)),config:{...previous.config,teams:count%2===0}}))}
 function toggle(game:Game){setRound(previous=>({...previous,games:previous.games.includes(game)?previous.games.filter(item=>item!==game):[...previous.games,game]}))}
 return <div className="feature-page"><button className="text-button" onClick={onBack}><ArrowLeft size={16}/> Back</button><div className="feature-heading"><span className="eyebrow">SAVED HOME GAME</span><h1>Make it<br/><em>your game.</em></h1><p>Combine supported games, choose the values, and save the setup for the next daily, weekly, or occasional round.</p></div><label>Give it a familiar name<input placeholder="e.g. Saturday Nassau + Skins" maxLength={50} value={name} onChange={event=>setName(event.target.value)}/></label><label>Usual number of players</label><div className="segment">{[2,3,4,5,6,7,8].map(count=><button key={count} className={round.players.length===count?'selected':''} onClick={()=>setCount(count)}>{count}</button>)}</div><label>Round length</label><div className="segment">{([9,18] as const).map(holes=><button key={holes} className={round.holes===holes?'selected':''} onClick={()=>setRound(previous=>({...previous,holes,games:previous.games.filter(game=>gameFits(game,previous.players.length,holes))}))}>{holes} holes</button>)}</div><div className="section-heading"><h2>Choose the games</h2><span className="muted">One or more</span></div><div className="creator-blocks">{gameCatalog.filter(item=>gameFits(item.name,round.players.length,round.holes)).map(item=><button key={item.name} className={round.games.includes(item.name)?'selected':''} onClick={()=>toggle(item.name)}><strong>{item.name}</strong><small>{item.description}</small>{round.games.includes(item.name)?<Check size={17}/>:<Plus size={17}/>}</button>)}</div><div className="section-heading"><h2>Add any bonus games</h2></div><div className="creator-bonuses">{(['Birdies','Greenies','Sandies','Snake'] as Game[]).map(game=><button className={round.games.includes(game)?'selected':''} key={game} onClick={()=>toggle(game)}>{game}{round.games.includes(game)?<Check size={15}/>:<Plus size={15}/>}</button>)}</div><div className="section-heading"><h2>Rules and whole-dollar values</h2></div><GameSettings round={round} onChange={setRound}/><div className="feature-card"><span className="eyebrow">CHECK BEFORE SAVING</span><h2>{name.trim()||'Your new home game'}</h2><p>{round.players.length} golfers · {round.holes} holes · {round.games.join(' + ')||'Choose a game'}</p>{round.games.map(game=>{const estimate=estimateExposure(round,game);return <div className="creator-preview-row" key={game}><strong>{game}</strong><span>{rulesSummary(round,game)}</span><small>Modeled possible max: ${Math.ceil(estimate.possibleMax)} per player</small></div>})}<p className="fine">This is a planning estimate, not a loss cap. You can check and change the players, course, and amounts before each round.</p></div>{setupError(round)&&<p className="error">{setupError(round)}</p>}<button className="primary full" disabled={!valid} onClick={()=>onSave(name.trim(),round)}>Save home game <ArrowRight size={17}/></button></div>
}
