'use client';
import {useState} from 'react';
import {ArrowRight,RefreshCw,Shuffle} from 'lucide-react';
import {recommendGames,CaddieInput,Recommendation,RoundVibe} from '@/lib/recommendations/gameCaddie';
import {players as demoPlayers,Round} from '@/lib/types';
export function RandomGamePicker({onUse,history,activeRound=false}:{onUse:(item:Recommendation,input:CaddieInput)=>void;history:Round[];activeRound?:boolean}){
 const [count,setCount]=useState(4),[holes,setHoles]=useState<9|18>(18),[maxExposure,setMaxExposure]=useState(20),[vibe,setVibe]=useState<RoundVibe>('new'),[selected,setSelected]=useState<string|null>(null),[shown,setShown]=useState(false);
 const lineup=Array.from({length:count},(_,index)=>demoPlayers[index]?{...demoPlayers[index]}:{id:`guest-${index}`,name:`Player ${index+1}`,handicap:18,color:'#e2e6d5'});
 const input:CaddieInput={players:lineup,holes,maxExposure,vibe,complexity:'any',teams:'any',history};
 const three=recommendGames(input).slice(0,3);
 const pick=()=>setSelected(three[Math.floor(Math.random()*three.length)]?.game??null);
 const reset=()=>{setSelected(null);setShown(false)};
 return <section className="random-picker" aria-labelledby="random-picker-title"><div className="random-picker-heading"><span className="picker-icon"><Shuffle size={21}/></span><div><span className="eyebrow">SHAKE UP THE ROUND</span><h2 id="random-picker-title">Surprise me.</h2><p>Three games that fit, then we can pick for you.</p></div></div><div className="random-fields"><label>Players<select value={count} onChange={event=>{setCount(Number(event.target.value));reset()}}>{Array.from({length:7},(_,index)=>index+2).map(value=><option key={value} value={value}>{value} players</option>)}</select></label><div className="picker-holes"><span>Holes</span><div className="segment">{([9,18] as const).map(value=><button key={value} type="button" className={holes===value?'selected':''} onClick={()=>{setHoles(value);reset()}}>{value}</button>)}</div></div><label>Maximum exposure<input type="number" min="1" max="10000" value={maxExposure} onChange={event=>{setMaxExposure(Math.max(1,Number(event.target.value)));reset()}}/></label><label>Vibe<select value={vibe} onChange={event=>{setVibe(event.target.value as RoundVibe);reset()}}><option value="new">Try something new</option><option value="friendly">Friendly</option><option value="competitive">Competitive</option><option value="team">Team battle</option></select></label></div><button className="primary picker-draw" disabled={!three.length} onClick={()=>{setShown(true);setSelected(null)}}><Shuffle size={17}/> Find three games</button>{shown&&<div className="random-result"><span className="eyebrow">WHY THESE THREE</span><p>{count} golfers, {holes} holes and a ${maxExposure} exposure target. Each game is compatible and its recommended settings model below that target.</p><div className="surprise-options">{three.map(item=><button key={item.game} className={selected===item.game?'selected':''} onClick={()=>setSelected(item.game)}><strong>{item.game}</strong><small>{item.metadata.complexity} · ${item.exposure.projectedLow.toFixed(2)}–${item.exposure.projectedHigh.toFixed(2)} projected</small></button>)}</div><div className="random-actions"><button className="primary" onClick={pick}><Shuffle size={15}/> Pick for us</button><button className="secondary" onClick={()=>{reset()}}><RefreshCw size={15}/> Start over</button></div>{selected&&<div className="surprise-choice"><h3>{selected}</h3><p>{three.find(item=>item.game===selected)?.why}</p><button className="primary" onClick={()=>onUse(three.find(item=>item.game===selected)!,input)}>{activeRound?'Continue current round':'Set up this game'} <ArrowRight size={16}/></button></div>}{activeRound&&<p className="fine">Finish your active round before starting another.</p>}</div>}</section>
}
