'use client';
import {useState} from 'react';
import {Check,Copy,Eye,Share2,ShieldCheck,Users,X} from 'lucide-react';
import type {RoundActivity} from '@/lib/contracts/round-sync';
import type {Round} from '@/lib/types';

export type SharedSession={roundId:string;token:string;scope:'view'|'score';revision:number;role:'captain'|'viewer'|'editor';canEdit:boolean;activity:RoundActivity[]};

function shareUrl(session:SharedSession){const url=new URL(window.location.href);url.search='';url.hash=new URLSearchParams({round:session.roundId,token:session.token}).toString();return url.toString()}

export function RoundSharing({round,shared,onShared,onClose,onToast}:{round:Round;shared:SharedSession|null;onShared:(session:SharedSession)=>void;onClose:()=>void;onToast:(message:string)=>void}){
 const [scope,setScope]=useState<'view'|'score'>(shared?.scope??'view'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function create(){setBusy(true);setError('');try{const response=await fetch('/api/v1/rounds',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({round,scope})});const result=await response.json() as {shared?:{roundId:string;token:string;scope:'view'|'score';revision:number};error?:string};if(!response.ok||!result.shared)throw new Error(result.error||'Could not start sharing.');const session:SharedSession={...result.shared,role:'captain',canEdit:true,activity:shared?.activity??[]};onShared(session);const url=shareUrl(session);window.history.replaceState(null,'',url);onToast('Live round link is ready')}catch(cause){setError(cause instanceof Error?cause.message:'Could not start sharing.')}finally{setBusy(false)}}
 async function send(){if(!shared)return;const url=shareUrl(shared),text=shared.scope==='score'?'Open Loop to follow the round and help enter scores.':'Open Loop to follow the live score and bets.';try{if(navigator.share)await navigator.share({title:`Live round at ${round.course}`,text,url});else{await navigator.clipboard.writeText(url);onToast('Live round link copied')}}catch{/* User cancelled the system share sheet. */}}
 async function copy(){if(!shared)return;try{await navigator.clipboard.writeText(shareUrl(shared));onToast('Live round link copied')}catch{onToast(shareUrl(shared))}}
 const captain=!shared||shared.role==='captain';
 return <div className="modal-backdrop" onClick={onClose}><section className="modal share-round-modal" role="dialog" aria-modal="true" aria-labelledby="share-round-title" onClick={event=>event.stopPropagation()}><button className="modal-close icon-button" aria-label="Close" onClick={onClose}><X/></button><Share2 size={27}/><h2 id="share-round-title">{captain?'Share the live round':'Live round access'}</h2><p className="muted">Everyone sees the same scorecard and live bets on their phone. Loop records each accepted score update.</p>{captain&&<><div className="share-permissions"><button className={scope==='view'?'selected':''} onClick={()=>setScope('view')}><ShieldCheck/><span><strong>Captain enters scores</strong><small>Recommended. Everyone else has a live read-only view.</small></span>{scope==='view'&&<Check/>}</button><button className={scope==='score'?'selected':''} onClick={()=>setScope('score')}><Users/><span><strong>Group can enter scores</strong><small>Anyone with this link can update a hole. Their name and time are recorded.</small></span>{scope==='score'&&<Check/>}</button></div>{shared&&shared.scope===scope?<div className="share-ready"><Eye/><span><strong>Live link ready</strong><small>{scope==='view'?'Captain scoring · group viewing':'Group scoring · edits identified'}</small></span></div>:<button className="primary full" disabled={busy} onClick={create}>{busy?'Creating secure link…':shared?'Create a new link with this access':'Turn on live sharing'} <Share2 size={17}/></button>}{shared&&shared.scope===scope&&<div className="feature-actions"><button className="primary" onClick={send}><Share2 size={16}/> Share link</button><button className="secondary" onClick={copy}><Copy size={16}/> Copy</button></div>}</>}{!captain&&<div className="share-ready"><Eye/><span><strong>{shared?.canEdit?'You can enter scores':'Captain scoring is on'}</strong><small>{shared?.canEdit?'Your saved changes will show your name and time.':'Your scorecard updates automatically every few seconds.'}</small></span></div>}{error&&<p className="error">{error}</p>}{shared?.activity.length?<div className="round-activity"><span className="eyebrow">RECENT SCORE UPDATES</span>{shared.activity.slice(0,5).map(item=><div key={`${item.revision}-${item.holeNumber}`}><i style={{background:item.editorColor}}/><span><strong>{item.editorName}</strong> saved hole {item.holeNumber}<small>{new Date(item.savedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></span></div>)}</div>:null}</section></div>;
}
