'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {ArrowLeft,CheckCircle2,LifeBuoy,Send} from 'lucide-react';
import type {Account} from '@/lib/account';

export function SupportForm(){
 const [form,setForm]=useState({email:'',category:'account',message:''}),[busy,setBusy]=useState(false),[reference,setReference]=useState(''),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/v1/auth/session',{cache:'no-store'}).then(async response=>{if(response.ok){const body=await response.json() as {account:Account};setForm(value=>({...value,email:body.account.email}))}}).catch(()=>{})},[]);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/v1/support',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const body=await response.json() as {reference?:string;error?:string};if(!response.ok||!body.reference)throw new Error(body.error||'Support request could not be saved.');setReference(body.reference)}catch(cause){setError(cause instanceof Error?cause.message:'Support request could not be saved.')}finally{setBusy(false)}}
 return <main id="main-content" className="support-page"><header><Link className="auth-brand" href="/">loop<span>.</span></Link><Link className="legal-back" href="/"><ArrowLeft/> Back to Loop</Link></header><section className="support-layout"><div className="support-intro"><span className="recovery-icon"><LifeBuoy/></span><p className="legal-eyebrow">PRIVATE BETA SUPPORT</p><h1>Tell us where you got stuck.</h1><p>Use plain language. Include what you tapped, what you expected, and what happened. Never send your password.</p><ul><li>Account access and password help</li><li>Privacy or account deletion questions</li><li>Scorecard, group, or game problems</li></ul></div>{reference?<div className="support-form support-success"><CheckCircle2/><h2>Request saved.</h2><p>Your reference is <strong>{reference}</strong>. Keep it if you need to follow up.</p><Link className="primary" href="/">Return to Loop</Link></div>:<form className="support-form" onSubmit={submit}><label>Email address<input type="email" autoComplete="email" required maxLength={254} value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>What do you need help with?<select value={form.category} onChange={event=>setForm({...form,category:event.target.value})}><option value="account">Account or sign in</option><option value="privacy">Privacy or deletion</option><option value="bug">Something is not working</option><option value="other">Something else</option></select></label><label>What happened?<textarea required minLength={12} maxLength={2000} rows={7} value={form.message} onChange={event=>setForm({...form,message:event.target.value})} placeholder="Example: I tried to start our weekly game, but…"/><small>{form.message.length} / 2,000</small></label>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':<><Send/> Send support request</>}</button><p className="support-note">This request is saved securely for the Loop beta team.</p></form>}</section></main>;
}
