import {Game} from './types';
export const library:{name:Game;description:string;players:string;stakes:string;rules:string}[]=[
{name:'Nassau',description:'Three matches. A fresh chance at the turn.',players:'2–8, equal teams',stakes:'$5 / $5 / $5',rules:'Front nine, back nine and overall are separate matches. Teams use their lowest gross score on each hole; the total team stake is split equally. Individual mode plays each pair. A press is a new match through the end of that nine. Auto presses start on the next hole when an active match first reaches two down. Live amounts are provisional.'},
{name:'Skins',description:'Win the hole outright. Take the pot.',players:'2–8 players',stakes:'$2 per opponent',rules:'The single lowest score wins the skin from each opponent. Ties carry the stake to the next hole when enabled. Unwon skins expire at round end. Net uses full handicap strokes by hole difficulty.'},
{name:'Wolf',description:'One golfer takes on the pack.',players:'3–8 players',stakes:'$2 per opponent',rules:'The Wolf rotates each hole and chooses a partner after that player’s drive, plays alone, or declares Blind Wolf before tee shots. Compare best-ball scores. Partner matches use the base per-opponent stake; Lone and Blind use configurable win/loss multipliers. Ties push unless the group chooses Wolf-loses for solo holes. Set the starting Wolf, gross/net, multipliers and each hole’s lineup in round setup and scoring.'},
{name:'Match Play',description:'Every hole is a new head-to-head.',players:'2–8 players',stakes:'$2 per hole',rules:'Every player faces every other player. Set the amount per pairing, gross or net, and choose a separate payout on each hole or one payout after the whole match. Tied holes push.'},
{name:'Sixes',description:'New partners every six holes.',players:'Exactly 4 players · 18 holes',stakes:'$2 per team / hole',rules:'Four golfers play best ball in three six-hole blocks. Partners rotate on holes 7 and 13, so everyone partners with everyone once. Each hole is worth the chosen team value; teammates split wins and losses. Ties push.'},
{name:'Vegas',description:'Pair up. Turn two hole scores into one number.',players:'Exactly 4 players',stakes:'$1 per point / team',rules:'Four players form two teams of two. On each hole, place the lower score first: 4 and 5 become 45. The lower team number wins. Subtract the numbers to get the point difference, then multiply by your value per point. The team payment is split equally between the two players. You can change partners each hole.'},
{name:'Hammer',description:'A low score with a little extra bite.',players:'2–8 players',stakes:'$2 base / team',rules:'Team best ball for a configurable base stake per hole. Either team throws the first Hammer; the other accepts a doubled stake or declines and concedes the existing stake. Accepted throws alternate up to the configured limit. Optionally double a winning gross birdie. Record each offer and response on that hole.'},
{name:'Greenies',description:'Closest to the pin. Bragging rights included.',players:'2–8 players',stakes:'$5 per opponent',rules:'Select the closest-to-pin winner on configured par-3 holes. Winner receives the chosen amount from every opponent. Optionally require gross par or better; leave unclaimed if nobody qualifies.'},
{name:'Birdies',description:'A little reward for one under.',players:'2–8 players',stakes:'$2 per opponent',rules:'Each gross birdie earns the chosen amount from every opponent. Set a separate multiplier for eagle or better. Multiple winners each receive an award and payments can offset.'},
{name:'Sandies',description:'Get up and down from the sand.',players:'2–8 players',stakes:'$2 per opponent',rules:'Mark each agreed sandy in hole events. Choose the amount per opponent and whether gross par or better is required.'},
{name:'Snake',description:'Avoid the last three-putt.',players:'2–8 players',stakes:'$2 per opponent',rules:'Mark all three-putts in order by hole. Choose whether only the last holder pays the selected amount to every opponent at round end, or each marked three-putt pays when it occurs. Last-holder live balance is provisional.'},
{name:'Dots',description:'Keep track of the little victories.',players:'2–8 players',stakes:'$2 per dot',rules:'Mark one agreed achievement per player per hole. Each marked dot earns the selected amount from every opponent.'}];
